export const specialities = [
  'Dermatologists',
  'Endocrinologists',
  'Emergency Medicine Specialists',
  'Family Physicians',
  'Gastroenterologists',
  'Geriatric Medicine Specialists',
  'Nephrologists',
  'Neurologists',
  'Obstetricians and Gynecologists',
  'Oncologists',
  'Ophthalmologists',
  'Podiatrists',
  'Preventive Medicine Specialists',
  'Psychiatrists',
  'Pulmonologists',
  'Radiologists',
  'Rheumatologists',
  'Allergists/Immunologists',
  'Anesthesiologists',
  'Cardiologists',
  'Colon and Rectal Surgeons',
  'Critical Care Medicine Specialists',
  'Hematologists',
  'Hospice and Palliative Medicine Specialists',
  'Infectious Disease Specialists',
  'Internists',
  'Medical Geneticists',
  'Osteopaths ',
  'Otolaryngologists',
  'Pathologists',
  'Pediatricians',
  'Physiatrists',
  'Plastic Surgeons',
  'Sleep Medicine Specialists',
  'Sports Medicine Specialists',
  'General Surgeons',
  'Urologists',
];
